[build]
  publish = "web"
  functions = "netlify/functions"

[[redirects]]
  from = "/privacy"
  to = "/privacy-policy.html"
  status = 301

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 301
